service: nest-http-lambda-broilerplate

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline

package:
  individually: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  main: # The name of the lambda function
    # The module 'handler' is exported in the file 'src/lambda'
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{proxy+}
